### ISSUE TITLE
Stitched call graph contains improper URIs

### ISSUE THREAD

**Issue by MagielBruntink** [fasten-project/fasten-pypi-plugin#17] opened 2022-06-02 13:51 UTC
Hi team,

I'm testing the fasten-pypi-plugin and I'm observing that the FASTEN URIs in the stitched call graphs are not quite right. I'm running the following:
```
python -m fasten \
  --product fasten-pypi-plugin \
  --pkg_name fasten-pypi-plugin 
  --project_path ./ \
  --timestamp 42 \ 
  --version 1.0 \ 
  --requirements requirements.txt \
  --fasten_data revisionCallGraphs/ \ 
  --scg_path mergedCallGraphs/
```

In the file `fasten-pypi-plugin/mergedCallGraphs/fasten-pypi-plugin.json` the following URIs appear:
```
"URI": "//fasten-pypi-plugin/..\\build\\lib\\fasten\\createAdjacencyList/CreateAdjacencyList.createAdjacencyList()"
"URI": "//fasten-pypi-plugin/..\\build\\lib\\fasten\\createAdjacencyList/CreateAdjacencyList.print_agraph()"
"URI": "//fasten-pypi-plugin/..\\build\\lib\\fasten\\createAdjacencyList/CreateAdjacencyList.getNumberOfVertices()"
```
These are not proper FASTEN URIs. Instead, they should look something like:
```
fasten://PyPI!fasten-pypi-plugin$1.0/createAdjacencyList/CreateAdjacencyList.createAdjacencyList()
```

**Comment by MagielBruntink** [comment] 2022-06-03 07:14
@gdrosos This seems caused by how PyCG and the stitcher construct the FASTEN URIs. At least it seems the plugin just passes along the contents of the graphs.

**Comment by gdrosos** [comment] 2022-06-03 07:42
So if I understand correctly we need to add the forge in the URI of stitched nodes in order to be fully consistent with the naming conversion?

**Comment by MagielBruntink** [comment] 2022-06-03 07:47
It seems yes.
```
curl -X POST -d '["fasten://edgar3$1.1.7/edgar3.filing/Filing.__repr__()"]' -H 'Content-Type: application/json' https://api.fasten-project.eu/api/pypi/metadata/callables?allAttributes=true
```
Does not work.

But the following does:
```
curl -X POST -d '["fasten://PyPI!edgar3$1.1.7/edgar3.filing/Filing.__repr__()"]' -H 'Content-Type: application/json' https://api.fasten-project.eu/api/pypi/metadata/callables?allAttributes=true
```

**Comment by gdrosos** [comment] 2022-06-03 11:07
Fixed on the latest pycg-stitch docker image & pypi version 0.0.9. Tested also an example node,  by querrying the rest-api and I could recieve quality metadata:

```
gdrosos@monster:~/pycg-stitch$ curl -X POST -d '["fasten://PyPI!pycparser$2.09.1/pycparser.ply.cpp/Preprocessor.parsegen()"]' -H 'Content-Type: application/json' https://api.fasten-project.eu/api/pypi/metadata/callables?allAttributes=true
{"fasten://PyPI!pycparser$2.09.1/pycparser.ply.cpp/Preprocessor.parsegen()":{"quality":{"quality_analysis_timestamp":"1653540128.142197","callable_long_name":"parsegen( self , input , source = None )","quality_analyzer_version":"1.17.10","callable_parameters":["self","input","source"],"rapid_plugin_version":"1.2.4","metrics":{"nloc":107,"complexity":44,"token_count":586,"parameter_count":3,"length":123},"quality_analyzer_name":"Lizard","callable_name":"parsegen"}}}
```
PyPI Pakckage:https://pypi.org/project/pycg-stitch/0.0.9/
Docker image: [ghcr.io/fasten-project/pycg-stitch/fasten.pycgstitch@sha256:2842a749eaa3b1ffe9f4eaf5292c063dbf1db08be54bc5ed7d6595274ba2dbe9](https://ghcr.io/fasten-project/pycg-stitch/fasten.pycgstitch@sha256:2842a749eaa3b1ffe9f4eaf5292c063dbf1db08be54bc5ed7d6595274ba2dbe9)


Related commit: https://github.com/fasten-project/pycg-stitch/commit/aed9b205844aa8fe26634bcaa6082e0bbd175867

**Comment by MagielBruntink** [comment] 2022-06-03 11:39
Thanks @gdrosos that is very convenient.

I wonder how in the pypi-plugin the FASTEN URIs are totally different however, they don't even start with `fasten://`, have no package version included, and the file path/namespace looks off.

**Comment by gdrosos** [comment] 2022-06-03 12:22
The root cause of the issue is this line: https://github.com/fasten-project/fasten-pypi-plugin/blob/01de7280efab995b6fedc21d049faaac1bf2e540/src/fasten/stitchCallGraphs.py#L13

The Sticher class recieves as a second value a binary value, which if true will produce the Nodes in the Simple format, otherwise it will produce them in the fasten format. The plugin uses the Stitcher Class From PyCG-Stitch by passing a String argument, which is interpreted in Python as true, thus recieving the node URIs in a wrong format. I will submit a PR fixing this issue.

**Closed** 2022-06-03 21:15 UTC
